// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EmailIntegrationInitParameters struct {

	// The username part of the email address. It must be unique for each integration.
	EmailUsername *string `json:"emailUsername,omitempty" tf:"email_username,omitempty"`

	// A Member block as documented below.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// If enabled, the integration will ignore recipients sent in request payloads. Default: false.
	IgnoreRespondersFromPayload *bool `json:"ignoreRespondersFromPayload,omitempty" tf:"ignore_responders_from_payload,omitempty"`

	// Name of the integration. Name must be unique for each integration.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Owner team id of the integration.
	// +crossplane:generate:reference:type=github.com/macpaw/provider-opsgenie/apis/team/v1alpha1.Team
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`

	// Reference to a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDRef *v1.Reference `json:"ownerTeamIdRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDSelector *v1.Selector `json:"ownerTeamIdSelector,omitempty" tf:"-"`

	Responders []RespondersInitParameters `json:"responders,omitempty" tf:"responders,omitempty"`

	// If enabled, notifications that come from alerts will be suppressed. Default: false.
	SuppressNotifications *bool `json:"suppressNotifications,omitempty" tf:"suppress_notifications,omitempty"`
}

type EmailIntegrationObservation struct {

	// The username part of the email address. It must be unique for each integration.
	EmailUsername *string `json:"emailUsername,omitempty" tf:"email_username,omitempty"`

	// A Member block as documented below.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The id of the responder.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If enabled, the integration will ignore recipients sent in request payloads. Default: false.
	IgnoreRespondersFromPayload *bool `json:"ignoreRespondersFromPayload,omitempty" tf:"ignore_responders_from_payload,omitempty"`

	// Name of the integration. Name must be unique for each integration.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Owner team id of the integration.
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`

	Responders []RespondersObservation `json:"responders,omitempty" tf:"responders,omitempty"`

	// If enabled, notifications that come from alerts will be suppressed. Default: false.
	SuppressNotifications *bool `json:"suppressNotifications,omitempty" tf:"suppress_notifications,omitempty"`
}

type EmailIntegrationParameters struct {

	// The username part of the email address. It must be unique for each integration.
	// +kubebuilder:validation:Optional
	EmailUsername *string `json:"emailUsername,omitempty" tf:"email_username,omitempty"`

	// A Member block as documented below.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// If enabled, the integration will ignore recipients sent in request payloads. Default: false.
	// +kubebuilder:validation:Optional
	IgnoreRespondersFromPayload *bool `json:"ignoreRespondersFromPayload,omitempty" tf:"ignore_responders_from_payload,omitempty"`

	// Name of the integration. Name must be unique for each integration.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Owner team id of the integration.
	// +crossplane:generate:reference:type=github.com/macpaw/provider-opsgenie/apis/team/v1alpha1.Team
	// +kubebuilder:validation:Optional
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`

	// Reference to a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDRef *v1.Reference `json:"ownerTeamIdRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDSelector *v1.Selector `json:"ownerTeamIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Responders []RespondersParameters `json:"responders,omitempty" tf:"responders,omitempty"`

	// If enabled, notifications that come from alerts will be suppressed. Default: false.
	// +kubebuilder:validation:Optional
	SuppressNotifications *bool `json:"suppressNotifications,omitempty" tf:"suppress_notifications,omitempty"`
}

type RespondersInitParameters struct {

	// The id of the responder.
	// +crossplane:generate:reference:type=github.com/macpaw/provider-opsgenie/apis/team/v1alpha1.Team
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Team in team to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.Reference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.Selector `json:"idSelector,omitempty" tf:"-"`

	// The responder type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RespondersObservation struct {

	// The id of the responder.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The responder type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RespondersParameters struct {

	// The id of the responder.
	// +crossplane:generate:reference:type=github.com/macpaw/provider-opsgenie/apis/team/v1alpha1.Team
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Team in team to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.Reference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.Selector `json:"idSelector,omitempty" tf:"-"`

	// The responder type.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// EmailIntegrationSpec defines the desired state of EmailIntegration
type EmailIntegrationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EmailIntegrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EmailIntegrationInitParameters `json:"initProvider,omitempty"`
}

// EmailIntegrationStatus defines the observed state of EmailIntegration.
type EmailIntegrationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EmailIntegrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EmailIntegration is the Schema for the EmailIntegrations API. Manages an Email Integration within Opsgenie.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,opsgenie}
type EmailIntegration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.emailUsername) || (has(self.initProvider) && has(self.initProvider.emailUsername))",message="spec.forProvider.emailUsername is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   EmailIntegrationSpec   `json:"spec"`
	Status EmailIntegrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EmailIntegrationList contains a list of EmailIntegrations
type EmailIntegrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EmailIntegration `json:"items"`
}

// Repository type metadata.
var (
	EmailIntegration_Kind             = "EmailIntegration"
	EmailIntegration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EmailIntegration_Kind}.String()
	EmailIntegration_KindAPIVersion   = EmailIntegration_Kind + "." + CRDGroupVersion.String()
	EmailIntegration_GroupVersionKind = CRDGroupVersion.WithKind(EmailIntegration_Kind)
)

func init() {
	SchemeBuilder.Register(&EmailIntegration{}, &EmailIntegrationList{})
}
