// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/macpaw/provider-opsgenie/apis/team/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this EmailIntegration.
func (mg *EmailIntegration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OwnerTeamID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.OwnerTeamIDRef,
		Selector:     mg.Spec.ForProvider.OwnerTeamIDSelector,
		To: reference.To{
			List:    &v1alpha1.TeamList{},
			Managed: &v1alpha1.Team{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OwnerTeamID")
	}
	mg.Spec.ForProvider.OwnerTeamID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OwnerTeamIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Responders); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Responders[i3].ID),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.Responders[i3].IDRef,
			Selector:     mg.Spec.ForProvider.Responders[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.TeamList{},
				Managed: &v1alpha1.Team{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Responders[i3].ID")
		}
		mg.Spec.ForProvider.Responders[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Responders[i3].IDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.OwnerTeamID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.OwnerTeamIDRef,
		Selector:     mg.Spec.InitProvider.OwnerTeamIDSelector,
		To: reference.To{
			List:    &v1alpha1.TeamList{},
			Managed: &v1alpha1.Team{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.OwnerTeamID")
	}
	mg.Spec.InitProvider.OwnerTeamID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.OwnerTeamIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Responders); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Responders[i3].ID),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.InitProvider.Responders[i3].IDRef,
			Selector:     mg.Spec.InitProvider.Responders[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.TeamList{},
				Managed: &v1alpha1.Team{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Responders[i3].ID")
		}
		mg.Spec.InitProvider.Responders[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Responders[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}
