// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type HeartbeatInitParameters struct {

	// Specifies the alert message for heartbeat expiration alert. If this is not provided, default alert message is "HeartbeatName is expired".
	AlertMessage *string `json:"alertMessage,omitempty" tf:"alert_message,omitempty"`

	// Specifies the alert priority for heartbeat expiration alert. If this is not provided, default priority is P3.
	AlertPriority *string `json:"alertPriority,omitempty" tf:"alert_priority,omitempty"`

	// Specifies the alert tags for heartbeat expiration alert.
	// +listType=set
	AlertTags []*string `json:"alertTags,omitempty" tf:"alert_tags,omitempty"`

	// An optional description of the heartbeat
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (True) Enable/disable heartbeat monitoring.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Specifies how often a heartbeat message should be expected.
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// Interval specified as minutes, hours or days.
	IntervalUnit *string `json:"intervalUnit,omitempty" tf:"interval_unit,omitempty"`

	// Name of the heartbeat
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Owner team of the heartbeat.
	// +crossplane:generate:reference:type=github.com/macpaw/provider-opsgenie/apis/team/v1alpha1.Team
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`

	// Reference to a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDRef *v1.Reference `json:"ownerTeamIdRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDSelector *v1.Selector `json:"ownerTeamIdSelector,omitempty" tf:"-"`
}

type HeartbeatObservation struct {

	// Specifies the alert message for heartbeat expiration alert. If this is not provided, default alert message is "HeartbeatName is expired".
	AlertMessage *string `json:"alertMessage,omitempty" tf:"alert_message,omitempty"`

	// Specifies the alert priority for heartbeat expiration alert. If this is not provided, default priority is P3.
	AlertPriority *string `json:"alertPriority,omitempty" tf:"alert_priority,omitempty"`

	// Specifies the alert tags for heartbeat expiration alert.
	// +listType=set
	AlertTags []*string `json:"alertTags,omitempty" tf:"alert_tags,omitempty"`

	// An optional description of the heartbeat
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (True) Enable/disable heartbeat monitoring.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies how often a heartbeat message should be expected.
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// Interval specified as minutes, hours or days.
	IntervalUnit *string `json:"intervalUnit,omitempty" tf:"interval_unit,omitempty"`

	// Name of the heartbeat
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Owner team of the heartbeat.
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`
}

type HeartbeatParameters struct {

	// Specifies the alert message for heartbeat expiration alert. If this is not provided, default alert message is "HeartbeatName is expired".
	// +kubebuilder:validation:Optional
	AlertMessage *string `json:"alertMessage,omitempty" tf:"alert_message,omitempty"`

	// Specifies the alert priority for heartbeat expiration alert. If this is not provided, default priority is P3.
	// +kubebuilder:validation:Optional
	AlertPriority *string `json:"alertPriority,omitempty" tf:"alert_priority,omitempty"`

	// Specifies the alert tags for heartbeat expiration alert.
	// +kubebuilder:validation:Optional
	// +listType=set
	AlertTags []*string `json:"alertTags,omitempty" tf:"alert_tags,omitempty"`

	// An optional description of the heartbeat
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (True) Enable/disable heartbeat monitoring.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Specifies how often a heartbeat message should be expected.
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// Interval specified as minutes, hours or days.
	// +kubebuilder:validation:Optional
	IntervalUnit *string `json:"intervalUnit,omitempty" tf:"interval_unit,omitempty"`

	// Name of the heartbeat
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Owner team of the heartbeat.
	// +crossplane:generate:reference:type=github.com/macpaw/provider-opsgenie/apis/team/v1alpha1.Team
	// +kubebuilder:validation:Optional
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`

	// Reference to a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDRef *v1.Reference `json:"ownerTeamIdRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDSelector *v1.Selector `json:"ownerTeamIdSelector,omitempty" tf:"-"`
}

// HeartbeatSpec defines the desired state of Heartbeat
type HeartbeatSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     HeartbeatParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HeartbeatInitParameters `json:"initProvider,omitempty"`
}

// HeartbeatStatus defines the observed state of Heartbeat.
type HeartbeatStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HeartbeatObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Heartbeat is the Schema for the Heartbeats API. Manages Heartbeat within Opsgenie.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,opsgenie}
type Heartbeat struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interval) || (has(self.initProvider) && has(self.initProvider.interval))",message="spec.forProvider.interval is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.intervalUnit) || (has(self.initProvider) && has(self.initProvider.intervalUnit))",message="spec.forProvider.intervalUnit is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   HeartbeatSpec   `json:"spec"`
	Status HeartbeatStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HeartbeatList contains a list of Heartbeats
type HeartbeatList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Heartbeat `json:"items"`
}

// Repository type metadata.
var (
	Heartbeat_Kind             = "Heartbeat"
	Heartbeat_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Heartbeat_Kind}.String()
	Heartbeat_KindAPIVersion   = Heartbeat_Kind + "." + CRDGroupVersion.String()
	Heartbeat_GroupVersionKind = CRDGroupVersion.WithKind(Heartbeat_Kind)
)

func init() {
	SchemeBuilder.Register(&Heartbeat{}, &HeartbeatList{})
}
