// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type UserAddressInitParameters struct {
	City *string `json:"city,omitempty" tf:"city,omitempty"`

	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	Line *string `json:"line,omitempty" tf:"line,omitempty"`

	State *string `json:"state,omitempty" tf:"state,omitempty"`

	Zipcode *string `json:"zipcode,omitempty" tf:"zipcode,omitempty"`
}

type UserAddressObservation struct {
	City *string `json:"city,omitempty" tf:"city,omitempty"`

	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	Line *string `json:"line,omitempty" tf:"line,omitempty"`

	State *string `json:"state,omitempty" tf:"state,omitempty"`

	Zipcode *string `json:"zipcode,omitempty" tf:"zipcode,omitempty"`
}

type UserAddressParameters struct {

	// +kubebuilder:validation:Optional
	City *string `json:"city" tf:"city,omitempty"`

	// +kubebuilder:validation:Optional
	Country *string `json:"country" tf:"country,omitempty"`

	// +kubebuilder:validation:Optional
	Line *string `json:"line" tf:"line,omitempty"`

	// +kubebuilder:validation:Optional
	State *string `json:"state" tf:"state,omitempty"`

	// +kubebuilder:validation:Optional
	Zipcode *string `json:"zipcode" tf:"zipcode,omitempty"`
}

type UserInitParameters struct {

	// The Full Name of the User.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// Location information for the user. Please look at Supported Locale Ids for available locales.
	Locale *string `json:"locale,omitempty" tf:"locale,omitempty"`

	// The Role assigned to the User. Either a built-in such as 'Admin' or 'User' - or the name of a custom role.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// Skype username of the user.
	SkypeUsername *string `json:"skypeUsername,omitempty" tf:"skype_username,omitempty"`

	// A list of tags to be associated with the user.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Timezone information of the user. Please look at Supported Timezone Ids for available timezones.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// Address of the user.
	UserAddress []UserAddressInitParameters `json:"userAddress,omitempty" tf:"user_address,omitempty"`

	// Details about the user in form of key and list. of values.
	// +mapType=granular
	UserDetails map[string]*string `json:"userDetails,omitempty" tf:"user_details,omitempty"`

	// The email address associated with this user. Opsgenie defines that this must not be longer than 100 characters and must contain lowercase characters only.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserObservation struct {

	// The Full Name of the User.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// The ID of the Opsgenie User.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Location information for the user. Please look at Supported Locale Ids for available locales.
	Locale *string `json:"locale,omitempty" tf:"locale,omitempty"`

	// The Role assigned to the User. Either a built-in such as 'Admin' or 'User' - or the name of a custom role.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// Skype username of the user.
	SkypeUsername *string `json:"skypeUsername,omitempty" tf:"skype_username,omitempty"`

	// A list of tags to be associated with the user.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Timezone information of the user. Please look at Supported Timezone Ids for available timezones.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// Address of the user.
	UserAddress []UserAddressObservation `json:"userAddress,omitempty" tf:"user_address,omitempty"`

	// Details about the user in form of key and list. of values.
	// +mapType=granular
	UserDetails map[string]*string `json:"userDetails,omitempty" tf:"user_details,omitempty"`

	// The email address associated with this user. Opsgenie defines that this must not be longer than 100 characters and must contain lowercase characters only.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserParameters struct {

	// The Full Name of the User.
	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// Location information for the user. Please look at Supported Locale Ids for available locales.
	// +kubebuilder:validation:Optional
	Locale *string `json:"locale,omitempty" tf:"locale,omitempty"`

	// The Role assigned to the User. Either a built-in such as 'Admin' or 'User' - or the name of a custom role.
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// Skype username of the user.
	// +kubebuilder:validation:Optional
	SkypeUsername *string `json:"skypeUsername,omitempty" tf:"skype_username,omitempty"`

	// A list of tags to be associated with the user.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Timezone information of the user. Please look at Supported Timezone Ids for available timezones.
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// Address of the user.
	// +kubebuilder:validation:Optional
	UserAddress []UserAddressParameters `json:"userAddress,omitempty" tf:"user_address,omitempty"`

	// Details about the user in form of key and list. of values.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	UserDetails map[string]*string `json:"userDetails,omitempty" tf:"user_details,omitempty"`

	// The email address associated with this user. Opsgenie defines that this must not be longer than 100 characters and must contain lowercase characters only.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. Manages a User within Opsgenie.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,opsgenie}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fullName) || (has(self.initProvider) && has(self.initProvider.fullName))",message="spec.forProvider.fullName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
