apiVersion: notification.macpaw.dev/v1alpha1
kind: NotificationRule
metadata:
  annotations:
    meta.upbound.io/example-id: notification/v1alpha1/notificationrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    actionType: schedule-end
    notificationTime:
    - just-before
    - 15-minutes-ago
    steps:
    - contact:
      - method: email
        to: example@user.com
    usernameSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: user.macpaw.dev/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: notification/v1alpha1/notificationrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    fullName: Name Lastname
    role: User
    username: Example user
