apiVersion: notification.macpaw.dev/v1alpha1
kind: NotificationPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: notification/v1alpha1/notificationpolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    delayAction:
    - delayOption: next-time
      untilHour: 9
      untilMinute: 1
    filter:
    - {}
    policyDescription: This policy has a delay action
    teamIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: team.macpaw.dev/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: notification/v1alpha1/notificationpolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: This team deals with all the things
    name: example team
