apiVersion: team.macpaw.dev/v1alpha1
kind: Schedule
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/schedule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: schedule test
    enabled: false
    name: genieschedule-%s
    timezone: Europe/Rome
