apiVersion: team.macpaw.dev/v1alpha1
kind: TeamRoutingRule
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/teamroutingrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    criteria:
    - conditions:
      - expectedValue: expected1
        field: message
        not: false
        operation: contains
      type: match-any-condition
    notify:
    - nameSelector:
        matchLabels:
          testing.upbound.io/example-name: test
      type: schedule
    order: 0
    teamIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    timeRestriction:
    - restrictions:
      - endDay: tuesday
        endHour: 18
        endMin: 30
        startDay: monday
        startHour: 8
        startMin: 0
      type: weekday-and-time-of-day
    timezone: America/Los_Angeles

---

apiVersion: team.macpaw.dev/v1alpha1
kind: Schedule
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/teamroutingrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: schedule test
    enabled: false
    name: genieschedule
    timezone: Europe/Rome

---

apiVersion: team.macpaw.dev/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/teamroutingrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: This team deals with all the things
    name: example team
