// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ScheduleInitParameters struct {

	// The description of schedule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Enable/disable state of schedule
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Name of the schedule.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Owner team id of the schedule.
	// +crossplane:generate:reference:type=github.com/macpaw/provider-opsgenie/apis/team/v1alpha1.Team
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`

	// Reference to a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDRef *v1.Reference `json:"ownerTeamIdRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDSelector *v1.Selector `json:"ownerTeamIdSelector,omitempty" tf:"-"`

	// Timezone of schedule. Please look at Supported Timezone Ids for available timezones - Default: America/New_York.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type ScheduleObservation struct {

	// The description of schedule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Enable/disable state of schedule
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the Opsgenie Schedule.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the schedule.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Owner team id of the schedule.
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`

	// Timezone of schedule. Please look at Supported Timezone Ids for available timezones - Default: America/New_York.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type ScheduleParameters struct {

	// The description of schedule.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Enable/disable state of schedule
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Name of the schedule.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Owner team id of the schedule.
	// +crossplane:generate:reference:type=github.com/macpaw/provider-opsgenie/apis/team/v1alpha1.Team
	// +kubebuilder:validation:Optional
	OwnerTeamID *string `json:"ownerTeamId,omitempty" tf:"owner_team_id,omitempty"`

	// Reference to a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDRef *v1.Reference `json:"ownerTeamIdRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate ownerTeamId.
	// +kubebuilder:validation:Optional
	OwnerTeamIDSelector *v1.Selector `json:"ownerTeamIdSelector,omitempty" tf:"-"`

	// Timezone of schedule. Please look at Supported Timezone Ids for available timezones - Default: America/New_York.
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

// ScheduleSpec defines the desired state of Schedule
type ScheduleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScheduleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScheduleInitParameters `json:"initProvider,omitempty"`
}

// ScheduleStatus defines the observed state of Schedule.
type ScheduleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScheduleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Schedule is the Schema for the Schedules API. Manages a Schedule within Opsgenie.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,opsgenie}
type Schedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ScheduleSpec   `json:"spec"`
	Status ScheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScheduleList contains a list of Schedules
type ScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Schedule `json:"items"`
}

// Repository type metadata.
var (
	Schedule_Kind             = "Schedule"
	Schedule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Schedule_Kind}.String()
	Schedule_KindAPIVersion   = Schedule_Kind + "." + CRDGroupVersion.String()
	Schedule_GroupVersionKind = CRDGroupVersion.WithKind(Schedule_Kind)
)

func init() {
	SchemeBuilder.Register(&Schedule{}, &ScheduleList{})
}
