apiVersion: service.macpaw.dev/v1alpha1
kind: ServiceIncidentRule
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/serviceincidentrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    incidentRule:
    - conditionMatchType: match-any-condition
      conditions:
      - expectedValue: expected1
        field: message
        not: false
        operation: contains
      - expectedValue: expected2
        field: message
        not: false
        operation: contains
      incidentProperties:
      - message: This is a test message
        priority: P3
        stakeholderProperties:
        - enable: "true"
          message: Message for stakeholders
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: service.macpaw.dev/v1alpha1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/serviceincidentrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: example-service
    teamIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: team.macpaw.dev/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/serviceincidentrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: This team deals with all the things
    name: example-team
